### ISSUE TITLE
Adding Custom Field for Podmotor_File_ID doesn't hold value

### ISSUE THREAD

**Issue by itsjusteileen** [CastosHQ/Seriously-Simple-Podcasting#556]
**Describe the bug**
When trying to update the podmotor_episode_ID and podmotor_file_ID they are not initially visible in the WordPress editor when access to Custom Fields is first turned on. You need to visit the post on the front end and navigate back to the editor and you will see the podmotor_file_ID visible.

![image](https://user-images.githubusercontent.com/6146600/100674345-fd8a1b00-3332-11eb-889d-98a9bf7f4220.png)

Adding the podmotor_file_ID and clicking update for the field and then Update for the post, grabs and populates the podmotor_episode_ID but the podmotor_file_ID will not save.

**To Reproduce**
1. Go a post with podmotor_file_ID, notice there is no way to add a new custom field from the dropdown.
2. Add the ID number, Update the field and Update the episode.
3. Navigate to the post on the front end
4. Click on Edit Episode
5. Scroll to see podmotor_episode_ID present and no podmotor_file_ID

**Expected behavior**
The podmotor_file_ID should save in the custom fields.

**Screenshots**
http://somup.com/cYXv3v2iBX

**Additional context**
This behavior was present on two different installs and verified during a walkthrough with Alec Joy.

**Comment by ajoy39** [comment]
We also observed that, sometimes but not always, when trying to update a podcast that didn't have these fields already filled in it would instead create a new episode on the castos side. This, at least, I think I have some idea of why. `SeriouslySimplePodcasting\Handlers\Castos_Handler#260-264` Uses the existence or absence of the podmotor_episode_id to deterine rather to send the post as a create or an update action, these episodes had none because they were imported from Castos via rss feed

**Comment by jonathanbossenger** [comment]
This is not specifically a bug in the plugin, more a problem with how to manage custom fields in WordPress.

Because WordPress post meta data is a list of key-value pairs, there's no "master list" of custom fields that can be added to any post. WordPress tries to do it's best by seeing what other posts of this type have, and populating the drop-down with these values, but it's not always accurate.

It is however still possible to add custom fields, by scrolling to the bottom of the custom fields meta boxes and clicking "Enter new" (see screencast https://drive.google.com/file/d/1Xe9EccIn76T1ebteRPmeiqahJmeCdg_S/view?usp=sharing)

**Comment by jonathanbossenger** [comment]
> We also observed that, sometimes but not always, when trying to update a podcast that didn't have these fields already filled in it would instead create a new episode on the castos side. This, at least, I think I have some idea of why. `SeriouslySimplePodcasting\Handlers\Castos_Handler#260-264` Uses the existence or absence of the podmotor_episode_id to deterine rather to send the post as a create or an update action, these episodes had none because they were imported from Castos via rss feed

@ajoy39 that raises a good point, and is probably based on the fact that when the initial implementation of the plugin sync action to Castos was developed, this was the required functionality. 

A lot has changed since then, so it's probably a good idea to look at how the current save/update actions are hooked, and whether some improvements can be made `SeriouslySimplePodcasting\Controller\Admin_Controller#117-118` and `SeriouslySimplePodcasting\Controller\Admin_Controller#1521-1585`

I've created a new issue around that specifically that we can look into https://github.com/CastosHQ/Seriously-Simple-Podcasting/issues/557
