### ISSUE TITLE
Castos player does not display with [podcast_episode] shortcode since 2.5.2 update

### ISSUE THREAD

**Issue by TheCraigHewitt** [CastosHQ/Seriously-Simple-Podcasting#596]
**Describe the bug**
Since the 2.5.2 update the [podcast_episode] shortcode only displays the compact player.  

**To Reproduce**
1. Create a new page and user the [podcast_episode] shortcode with the post ID of an already published post (https://support.castos.com/article/42-podcastepisode-shortcode)
2. View the post on the front end
3. If you revert the plugin to v2.5.1 you'll see the HTML5 player

**Expected behavior**
The [podcast_episode] shortcode ought to display whichever player type is selected in the Podcast -> Settings -> Player menu area.

**Screenshots**
shortcode: https://share.getcloudapp.com/o0uEbzwQ
creates result: https://share.getcloudapp.com/9Zu8vnkr

**Additional context**
detailed in this thread: https://wordpress.org/support/topic/html-5-player-not-appearing-in-podcast_episode/

**Comment by jonathanbossenger** [comment]
@TheCraigHewitt apologies, this bug was introduced due to me over-correcting to fix a different bug in a different shortcode.

This does raise a valid point about our plugin automated testing, which will be a good thing to consider implementing before we include any new major changes. besides bug fixes, to the plugin. I will look into formalising our plugin testing process this week, so that we can start developing with tests from next week.
