### ISSUE TITLE
Series RSS Feed links back to default podcast URL, not Series URL. 

### ISSUE THREAD

**Issue by KTorrii** [CastosHQ/Seriously-Simple-Podcasting#744]
1) All podcast series RSS feeds link back to the default/main podcast URL despite the fact that we've indicated the series homepage URL.
2) Every page on the site contains HTML which points at the default/main podcast feed: <link rel="alternate" type="application/rss+xml" title="Podcast RSS feed" href="https://somesite.com/feed/podcast">

In order to get a rich Google snippet where the podcast and recent episodes show up properly, Google says a podcast series landing page and RSS feed need to link to each other: https://support.google.com/podcast-publishers/answer/9890054

**To Reproduce**
1. Go to any SSP Series Podcast Feed
2. Click on Visit Podcast Website
3. This will take you to the primary site URL, not the Series Podcast page.

**Expected behavior**
The link should go to the Series URL, or perhaps a specified URL within the Series' feed settings.

**Comment by zahardev** [comment]
For the 1-st one - I'm not sure we should change the url for "Visit podcast website" to the series url. But maybe it's a good idea to add another link there, like "Visit series page".
For the 2-nd - I don't see that every page points to the main podcast feed. And which tag is meant by pointing - <a>, <link> or something else?

**Comment by jdevalk** [comment]
> For the 1-st one - I'm not sure we should change the url for "Visit podcast website" to the series url. But maybe it's a good idea to add another link there, like "Visit series page".

Can we maybe change "visit series page" to actually just be the name of the podcast and "Visit podcast website" to actually be the name of the site? :)

> For the 2-nd - I don't see that every page points to the main podcast feed. And which tag is meant by pointing - `<a>`, `<link>` or something else?

The series archive page should have a rel link alternate to the series RSS feed, not to the main one. Is that what the problem is here?

**Comment by KingGrizzly** [comment]
The way Google wrote their email, makes me think a podcast should link to it’s landing (series) page. We have 3 podcasts, but they are not children to a parent so we don’t really utilize the one parent/global podcast in terms of a standalone website page or feeds. Our site is more like:

Global Podcast: Empty
Podcast 1: Landing Page + Feed
Podcast 2: Landing Page + Feed
Podcast 3: Landing Page + Feed

We really want to link back to the actual podcast landing pages which is what our followers would expect:

So we use Castos to run 3 podcasts, but they aren’t sub-series to a parent. Perhaps it’s intended by Castos to work more like:

Parent: Sports Podcast
-- Series 1: Football Podcast
-- Series 2: Soccer Podcast
-- Series 3: Track Podcast

I think what Joost is saying supports what the poster is asking for? In the first point, he is positing a workaround “hack" by dumping the “visit series page” language, but in the 2nd he does articulate what the poster is asking:

"The series archive page should have a rel link alternate to the series RSS feed, not to the main one. Is that what the problem is here?"

I believe this is the issue. That’s how I think Google is meaning it and I think it would be the reasonable expectation of the audience to land on the page for their podcast, not a parent.

Hope this helps. I could be confused on all of this!

Thanks,
Brian

**Comment by TheCraigHewitt** [comment]
I think the simplest and least disruptive (from an SEO and visitor perspective) would be for us to add the Series archive page link to the RSS feed in addition to the site homepage that's already there.  As Joost alluded to, it would be nice to make the anchor text of that link be the name of the Series as well, as that would offer more context to the link.  

For instance, if a Series was named "Second Series" and was at mysite.com/series/second-series we'd have that link on the RSS feed page itself just below the main website link.

**Comment by KingGrizzly** [comment]
Thanks @TheCraigHewitt 

I'm not 100% certain, seems plausible? 

When Google says "valid and crawlable URL of your podcast's homepage", I interpret this per series where each series is viewed as a unique podcast by Google, not a child. At least, this is true in our case, each series is really an independent podcast.

If I understand your proposed solution, the RSS feed would have:

- Parent podcast homepage link (in our case, this doesn't exist so we'd link to /podcasts landing page on our site)
- Series podcast homepage link (in our case, I think this would be the "podcast homepage" as Google describes)

Whether having 2 links will satisfy Google or if they will interpret those properly isn't clear to me. I'm wondering if Google will try to default all series to the one one global homepage url instead of the series urls.

Hope this makes some sense. Trying to understand!

**Comment by KingGrizzly** [comment]
@TheCraigHewitt Curious if you've had a chance to review my feedback and what the latest is. Thanks!

**Comment by TheCraigHewitt** [comment]
Hi @KingGrizzly we're going to be including the Series homepage link in addition to the main website link in the upcoming release of the plugin.  From all that we gather of the situation that's the most complete and appropriate solution for search engines and users.
